### ISSUE TITLE
URL of FAB Free Content changes every time a new set of items is available

### ISSUE THREAD

**Issue by goodmario1** [MMadmer/EpicAssetsNotifyBot#2]
> The URL of FAB Free Content changes every time a new set of items is available. The new link is [https://www.fab.com/blade/0691ff19-b259-44e0-ad3b-093a53010f46?context=homepage](url) 

 _Originally posted by @goodmario1 in [1a6756e](https://github.com/MMadmer/EpicAssetsNotifyBot/commit/1a6756edd006c1ef1e8105dbd23873340d9e5f9b#r148806598)_

**Comment by MMadmer** [comment]
Yeah, I'm familiar with this problem. I'm busy for the next month. If I have time, I'll try to fix it.

**Comment by MMadmer** [comment]
Everything works correctly
